import { db } from '../index';
import { institutions } from '../schema';

export async function seedInstitutions() {
  console.log('Seeding institutions...');

  const institutionData = [
    // Top US Universities and Institutes
    {
      name: 'Massachusetts Institute of Technology',
      country: 'United States',
      state: 'Massachusetts',
      city: 'Cambridge',
      domain: 'mit.edu',
      type: 'institute',
      rank: 1,
      createdAt: Date.now(),
    },
    {
      name: 'Stanford University',
      country: 'United States',
      state: 'California', 
      city: 'Stanford',
      domain: 'stanford.edu',
      type: 'university',
      rank: 2,
      createdAt: Date.now(),
    },
    {
      name: 'Harvard University',
      country: 'United States',
      state: 'Massachusetts',
      city: 'Cambridge',
      domain: 'harvard.edu',
      type: 'university',
      rank: 3,
      createdAt: Date.now(),
    },
    {
      name: 'Carnegie Mellon University',
      country: 'United States',
      state: 'Pennsylvania',
      city: 'Pittsburgh',
      domain: 'cmu.edu',
      type: 'university',
      rank: 4,
      createdAt: Date.now(),
    },
    {
      name: 'California Institute of Technology',
      country: 'United States',
      state: 'California',
      city: 'Pasadena',
      domain: 'caltech.edu',
      type: 'institute',
      rank: 5,
      createdAt: Date.now(),
    },
    {
      name: 'University of California, Berkeley',
      country: 'United States',
      state: 'California',
      city: 'Berkeley',
      domain: 'berkeley.edu',
      type: 'university',
      rank: 6,
      createdAt: Date.now(),
    },
    {
      name: 'Georgia Institute of Technology',
      country: 'United States',
      state: 'Georgia',
      city: 'Atlanta',
      domain: 'gatech.edu',
      type: 'institute',
      rank: 7,
      createdAt: Date.now(),
    },
    {
      name: 'University of California, Los Angeles',
      country: 'United States',
      state: 'California',
      city: 'Los Angeles',
      domain: 'ucla.edu',
      type: 'university',
      rank: 8,
      createdAt: Date.now(),
    },
    {
      name: 'University of Washington',
      country: 'United States',
      state: 'Washington',
      city: 'Seattle',
      domain: 'washington.edu',
      type: 'university',
      rank: 12,
      createdAt: Date.now(),
    },

    // UK Universities
    {
      name: 'University of Oxford',
      country: 'United Kingdom',
      state: 'England',
      city: 'Oxford',
      domain: 'ox.ac.uk',
      type: 'university',
      rank: 9,
      createdAt: Date.now(),
    },
    {
      name: 'University of Cambridge',
      country: 'United Kingdom',
      state: 'England',
      city: 'Cambridge',
      domain: 'cam.ac.uk',
      type: 'university',
      rank: 10,
      createdAt: Date.now(),
    },
    {
      name: 'Imperial College London',
      country: 'United Kingdom',
      state: 'England',
      city: 'London',
      domain: 'imperial.ac.uk',
      type: 'college',
      rank: 11,
      createdAt: Date.now(),
    },
    {
      name: 'University College London',
      country: 'United Kingdom',
      state: 'England',
      city: 'London',
      domain: 'ucl.ac.uk',
      type: 'college',
      rank: 15,
      createdAt: Date.now(),
    },

    // European Universities
    {
      name: 'ETH Zurich',
      country: 'Switzerland',
      state: 'Zurich',
      city: 'Zurich',
      domain: 'ethz.ch',
      type: 'institute',
      rank: 13,
      createdAt: Date.now(),
    },
    {
      name: 'École Polytechnique Fédérale de Lausanne',
      country: 'Switzerland',
      state: 'Vaud',
      city: 'Lausanne',
      domain: 'epfl.ch',
      type: 'polytechnic',
      rank: 14,
      createdAt: Date.now(),
    },
    {
      name: 'Technical University of Munich',
      country: 'Germany',
      state: 'Bavaria',
      city: 'Munich',
      domain: 'tum.de',
      type: 'university',
      rank: 16,
      createdAt: Date.now(),
    },
    {
      name: 'Delft University of Technology',
      country: 'Netherlands',
      state: 'South Holland',
      city: 'Delft',
      domain: 'tudelft.nl',
      type: 'university',
      rank: 17,
      createdAt: Date.now(),
    },
    {
      name: 'Politecnico di Milano',
      country: 'Italy',
      state: 'Lombardy',
      city: 'Milan',
      domain: 'polimi.it',
      type: 'polytechnic',
      rank: 20,
      createdAt: Date.now(),
    },
    {
      name: 'Politecnico di Torino',
      country: 'Italy',
      state: 'Piedmont',
      city: 'Turin',
      domain: 'polito.it',
      type: 'polytechnic',
      rank: 25,
      createdAt: Date.now(),
    },
    {
      name: 'National Technical University of Athens',
      country: 'Greece',
      state: 'Attica',
      city: 'Athens',
      domain: 'ntua.gr',
      type: 'university',
      rank: 35,
      createdAt: Date.now(),
    },

    // Asian Universities
    {
      name: 'National University of Singapore',
      country: 'Singapore',
      state: null,
      city: 'Singapore',
      domain: 'nus.edu.sg',
      type: 'university',
      rank: 18,
      createdAt: Date.now(),
    },
    {
      name: 'Nanyang Technological University',
      country: 'Singapore',
      state: null,
      city: 'Singapore',
      domain: 'ntu.edu.sg',
      type: 'university',
      rank: 19,
      createdAt: Date.now(),
    },
    {
      name: 'Tsinghua University',
      country: 'China',
      state: 'Beijing',
      city: 'Beijing',
      domain: 'tsinghua.edu.cn',
      type: 'university',
      rank: 21,
      createdAt: Date.now(),
    },
    {
      name: 'Peking University',
      country: 'China',
      state: 'Beijing',
      city: 'Beijing',
      domain: 'pku.edu.cn',
      type: 'university',
      rank: 22,
      createdAt: Date.now(),
    },
    {
      name: 'University of Tokyo',
      country: 'Japan',
      state: 'Tokyo',
      city: 'Tokyo',
      domain: 'u-tokyo.ac.jp',
      type: 'university',
      rank: 23,
      createdAt: Date.now(),
    },
    {
      name: 'KAIST',
      country: 'South Korea',
      state: 'Daejeon',
      city: 'Daejeon',
      domain: 'kaist.ac.kr',
      type: 'institute',
      rank: 24,
      createdAt: Date.now(),
    },
    {
      name: 'Seoul National University',
      country: 'South Korea',
      state: 'Seoul',
      city: 'Seoul',
      domain: 'snu.ac.kr',
      type: 'university',
      rank: 26,
      createdAt: Date.now(),
    },
    {
      name: 'POSTECH',
      country: 'South Korea',
      state: 'Gyeongsangbuk-do',
      city: 'Pohang',
      domain: 'postech.ac.kr',
      type: 'institute',
      rank: 27,
      createdAt: Date.now(),
    },
    {
      name: 'Technion - Israel Institute of Technology',
      country: 'Israel',
      state: 'Haifa District',
      city: 'Haifa',
      domain: 'technion.ac.il',
      type: 'institute',
      rank: 28,
      createdAt: Date.now(),
    },

    // Indian Universities and Institutes
    {
      name: 'Indian Institute of Technology Bombay',
      country: 'India',
      state: 'Maharashtra',
      city: 'Mumbai',
      domain: 'iitb.ac.in',
      type: 'institute',
      rank: 29,
      createdAt: Date.now(),
    },
    {
      name: 'Indian Institute of Technology Delhi',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      domain: 'iitd.ac.in',
      type: 'institute',
      rank: 30,
      createdAt: Date.now(),
    },
    {
      name: 'Indian Institute of Technology Madras',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      domain: 'iitm.ac.in',
      type: 'institute',
      rank: 31,
      createdAt: Date.now(),
    },
    {
      name: 'Indian Institute of Science',
      country: 'India',
      state: 'Karnataka',
      city: 'Bangalore',
      domain: 'iisc.ac.in',
      type: 'institute',
      rank: 32,
      createdAt: Date.now(),
    },
    {
      name: 'Indian Statistical Institute',
      country: 'India',
      state: 'West Bengal',
      city: 'Kolkata',
      domain: 'isical.ac.in',
      type: 'institute',
      rank: 40,
      createdAt: Date.now(),
    },
    {
      name: 'Birla Institute of Technology and Science',
      country: 'India',
      state: 'Rajasthan',
      city: 'Pilani',
      domain: 'bits-pilani.ac.in',
      type: 'institute',
      rank: 45,
      createdAt: Date.now(),
    },
    {
      name: 'Vellore Institute of Technology',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Vellore',
      domain: 'vit.ac.in',
      type: 'institute',
      rank: 50,
      createdAt: Date.now(),
    },
    {
      name: 'SRM Institute of Science and Technology',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      domain: 'srmist.edu.in',
      type: 'institute',
      rank: 55,
      createdAt: Date.now(),
    },

    // Canadian and Australian Universities
    {
      name: 'University of Toronto',
      country: 'Canada',
      state: 'Ontario',
      city: 'Toronto',
      domain: 'utoronto.ca',
      type: 'university',
      rank: 33,
      createdAt: Date.now(),
    },
    {
      name: 'University of Waterloo',
      country: 'Canada',
      state: 'Ontario',
      city: 'Waterloo',
      domain: 'uwaterloo.ca',
      type: 'university',
      rank: 34,
      createdAt: Date.now(),
    },
    {
      name: 'University of Melbourne',
      country: 'Australia',
      state: 'Victoria',
      city: 'Melbourne',
      domain: 'unimelb.edu.au',
      type: 'university',
      rank: 36,
      createdAt: Date.now(),
    },
    {
      name: 'Monash University',
      country: 'Australia',
      state: 'Victoria',
      city: 'Melbourne',
      domain: 'monash.edu.au',
      type: 'university',
      rank: 37,
      createdAt: Date.now(),
    },
    {
      name: 'RMIT University',
      country: 'Australia',
      state: 'Victoria',
      city: 'Melbourne',
      domain: 'rmit.edu.au',
      type: 'university',
      rank: 60,
      createdAt: Date.now(),
    },
  ];

  try {
    await db.insert(institutions).values(institutionData);
    console.log(`✅ Successfully seeded ${institutionData.length} institutions`);
  } catch (error) {
    console.error('❌ Error seeding institutions:', error);
    throw error;
  }
}

// Run the seeder if this file is executed directly
if (require.main === module) {
  seedInstitutions()
    .then(() => {
      console.log('Institutions seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Institutions seeding failed:', error);
      process.exit(1);
    });
}